#!/bin/sh
#copy to /etc/pm/sleep.d
LOGFILE="/var/log/sleep.log"

case "$1" in
        resume|thaw)
                echo "Resumed from suspend at `date`" >> "$LOGFILE"
                /usr/bin/python /usr/share/touchpad-indicator/check_touchpad_status.py
                echo "Touchpad enabled"
                ;;
esac
